### PR TITLE
Add view holder adapter that supports arrays and collections

### PR DESCRIPTION
**Pull request by kevinsawicki**
Simple alternative to list version

### CODE REVIEW

**Comment by rtyley** [comment]
Just wondering if adding this mirror implementation is really necessary - might it be better to just add a convenience constructor to `ViewHoldingListAdapter` that invokes Arrays.asList()?

**Comment by kevinsawicki** [comment]
Yeah, might not need both, but the common denominator of array instead of List is better in my opinion.

More things are array friendly (implement Collection) and array lookup is faster than List.get()

**Comment by rtyley** [comment]
Ah, personally I disagree - (even in general) I prefer List to array. I like the Collections framework, preferring to use it over array, and though there are situations where performance is better with array, I don't think that applies here. The bottleneck with ListViews is the creation & rendering of the views, not the random-access lookup of the backing element.

Of the Collections framework classes, List is definitely the most appropriate, [android.widget.Adapter](http://developer.android.com/reference/android/widget/Adapter.html) requires size, ordering and random-access, which narrows the choice of collection classes down to just List. All the other collection types and Arrays themselves can be coerced into List if required, and unless your array is several thousand elements long, the copying of the array into the internal List structure won't be a serious penalty.

If there's a good example of arrays providing a better experience, then cool, otherwise I think just a simple convenience constructor to ViewHoldingListAdapter is the best way to go.

**Comment by kevinsawicki** [comment]
The experience that I think is important is the flexibility to specify an array, a Collection, or varargs.

As long as all three could be supported at the constructor level, I don't think it matters much how things are stored internally.

**Comment by kevinsawicki** [comment]
Just one more comment, what is the upside of a `List` in this context as the internal storage field?

The only methods used internally are `size()`, `get()`, which array handles pretty well.

**Pull request closed without merging**
